### ISSUE TITLE
An Interesting Bug (PHP7.4)

### ISSUE THREAD

**Issue by Nikolayya** [nambu-ch/pimcore-minify-cssjs#1]
unfortunately this query does not always apply even if SRC is set. Maybe this kind of like it better :-)
greetings from Austria

Nikolaus

`if (array_key_exists("src", $item->attributes) && strpos($item->attributes["src"], 'http') !== 0 && strpos($item->attributes["src"], '//') !== 0) {
            `
https://github.com/nambu-ch/pimcore-minify-cssjs/blob/a14d3afc3cadcfc9d585ce47814d88ab5d5c5f54/src/MinifyCssJsBundle/Templating/Helper/HeadScript.php#L47

**Comment by lukas-schnieper** [comment]
Hi Nikolaus. Thank you for your note about this. This has been fixed in Version 1.0.4. I replaced the mentioned part with the following code, which does the same as array_key_exists.

`isset($item->attributes["src"])`
